/*
Working platform:- MySQL
*/

/* method 1 */
SELECT CONCAT(NAME,'(',SUBSTR(OCCUPATION,1,1),')') AS N 
FROM OCCUPATIONS
ORDER BY N;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;

/* method 2 */
SELECT CONCAT(NAME,'(',LEFT(OCCUPATION,1),')') 
FROM OCCUPATIONS
ORDER BY NAME;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;